words:
  - word: 'ГОД'
    hint: '52 недели'
  - word: 'ВРЕМЯ'
    hint: 'то что постоянно идёт'
  - word: 'ЖИЗНЬ'
    hint: 'у каждого своя'
  - word: 'ДЕНЬ'
    hint: 'антоним ночи'
  - word: 'РУКА'
    hint: 'верхняя конечность'
  - word: 'РАБОТА'
    hint: '8 часов в день'
  - word: 'ЛЮБОВЬ'
    hint: 'чувство к близким людям'
  - word: 'СЕМЬЯ'
    hint: 'самые близкие люди'
  - word: 'РОДИТЕЛИ'
    hint: 'отец и мать'
  - word: 'БРАТ'
    hint: 'фильм с Сергеем Бадровым'
  - word: 'ГОЛОС'
    hint: 'что отняли у русалочик'
  - word: 'ДРУГ'
    hint: 'близкий друг'
  - word: 'ЖЕНА'
    hint: 'супруга'
  - word: 'МУЖ'
    hint: 'супруг'
  - word: 'ДОМ'
    hint: 'место куда всегда возвращаешься'
  - word: 'СОБАКА'
    hint: 'лучший друг человека'
  - word: 'СТРАНА'
    hint: 'территория'
  - word: 'ГОРОД'
    hint: 'населённый пункт больше села'
  - word: 'ДЕРЕВНЯ'
    hint: 'село'
  - word: 'МИР'
    hint: 'земной шар'
  - word: 'ВИЗА'
    hint: 'и mastercard'
  - word: 'СИЛА'
    hint: 'в чём брат ?'
  - word: 'НАЧАЛО'
    hint: 'старт чего-то'
  - word: 'КОНЕЦ'
    hint: 'пришли'
  - word: 'БЕЛЫЙ'
    hint: 'снег'
  - word: 'СОЛНЦЕ'
    hint: 'монако'
  - word: 'МУЖЧИНА'
    hint: 'м'
  - word: 'ЖЕНЩИНА'
    hint: 'ж'
  - word: 'ОТНОШЕНИЯ'
    hint: 'между м и ж'
  - word: 'МАШИНА'
    hint: 'BMW'
  - word: 'КВАРТИРА'
    hint: 'аналог дома'
  - word: 'СОМ'
    hint: 'большая рыба'
  - word: 'ШАНС'
    hint: '1 на миллион'
  - word: 'ДЕНЬГИ'
    hint: 'за что мы работаем'
  - word: 'ЗОЛОТО'
    hint: 'драгоценный металл'